### PR TITLE
Add wasm tests

### PR DESCRIPTION
**Pull request by chemicstry**
Follow up on #6 to add CI tests

Based on: https://rustwasm.github.io/docs/wasm-bindgen/wasm-bindgen-test/usage.html

### CODE REVIEW

**Comment by chemicstry** [comment]
Not sure if we need to run wasm tests on full matrix?

**Comment by stjepang** [comment]
But it is tested on full matrix, is it not?

**Comment by chemicstry** [comment]
It is, but I thought it might be wasteful to run on full matrix as it builds for the same `wasm32-unknown-unknown` target for all instances.

**Comment by stjepang** [comment]
I see - will leave this PR open in case you want to restrict the build matrix but I'm okay with merging this PR either way.

**Comment by chemicstry** [comment]
I think you can merge it, the tests are quite fast anyway

**Review by stjepang — APPROVED** [review]
Thanks!

**Pull request merged**
